name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Nim environment
        uses: jiro4989/setup-nim-action@v1.5.1
        with:
          nim-version: '2.0.0' # default is 'stable'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - run: nimble test
      - run: echo "This job's status is ${{ job.status }}."
